version: 2
jobs:
  run:
    docker:
      - image: python:3.7-slim
    steps:
      - checkout
      - run: pip install -r requirements.txt

      # Write the "version" into the main file
      - run: sed -i -e "s/{{VERSION}}/$CIRCLE_SHA1/" main.py
      # Dump the bot token into a secrets.json
      - run: echo "{\"token\":\"$BOT_TOKEN\"}" > secrets.json

      - run: python -O main.py --testrun

  markdown_lint:
    docker:
      - image: 06kellyjac/markdownlint-cli:0.13.0-alpine
    steps:
      - checkout
      - run: markdownlint README.md

  pdoc:
    docker:
      - image: python:3.7-slim
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python setup.py install
      - run: pdoc --html telegram_bot
      - store_artifacts:
          path: html/telegram_bot

workflows:
  version: 2
  build:
    jobs:
      - markdown_lint
      - run
      - pdoc

