apiVersion: v1
kind: Namespace
metadata:
  name: telegram-bots
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: annoying-bot-state-pvc
  namespace: telegram-bots
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: Secret
metadata:
  name: annoying-bot-secrets
  namespace: telegram-bots
type: Opaque
data:
  BOT_TOKEN: "{{BOT_TOKEN}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: annoying-bot
  namespace: telegram-bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annoying-bot
  template:
    metadata:
      labels:
        app: annoying-bot
        dockertag: {{DOCKER_TAG}}
    spec:
      containers:
        - name: annoying-bot
          image: torbencarstens/annoying-bot:{{DOCKER_TAG}}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: annoying-bot-secrets
          volumeMounts:
            - mountPath: "/data"
              name: annoying-bot-state-volume
      volumes:
        - name: annoying-bot-state-volume
          persistentVolumeClaim:
            claimName: annoying-bot-state-pvc

